require("leehpham.plugins-setup")
require("leehpham.core.options")
require("leehpham.core.keymaps")
require("leehpham.core.colorscheme")
-- require("leehpham.plugins.comment")
require("leehpham.plugins.nvim-tree")
require("leehpham.plugins.lualine")
require("leehpham.plugins.telescope")
require("leehpham.plugins.bufferline")
